config/routes.rb
Hithr::Application.routes.draw do
  
  constraints(subdomain: "blog") do
    resources :posts, :shallow => true do
      resources :comments
    end
    root :to => 'posts#index'
  end
  
  constraints(subdomain: !"blog" ) do
  
    match "rides/offered" => "rides#offered", :as => "rides_offered"
    match "rides/wanted" => "rides#wanted", :as => "rides_wanted"
    get "users/:user_id/rides" => "rides#user_rides", :as => "user_rides"
    get "/rides" => redirect("/rides/offered")
    match "rides/:id/return" => "rides#return", :as => "return_trip"
    resources :rides, :shallow => true do
      resources :details
    end
  
    resources :abouts, :except => [:destroy], :path => "/about"
  
    resources :authentications, :only => [:new, :create, :destroy]
    match 'users/auth/:provider/callback/' => 'authentications#create'
   
    devise_for :users, :controllers => {  :registrations => 'registrations', 
                                          :sessions => 'users/sessions', 
                                          :passwords => 'users/passwords' } do
      match "/sign_in" => "users/sessions#new"
      match "/sign_out" => "devise/sessions#destroy" 
      match "/sign_up" => "registrations#new" 
    end
  
    resources :users, :shallow => true do
      resources :messages
      resources :profiles
      resources :references
    end
    get 'users/:user_id/messages/sent' => 'messages#sent', :as => "user_sent_messages"
    get 'users/:user_id/messages/all' => 'messages#all', :as => "user_all_messages"
  
  
    root :to => 'pages#home'
    get "/contact" => "pages#contact"
    get "/help" => "pages#help"
    get "/test" => "pages#test"
    get "/send_contact" => "pages#send_contact", :as => "send_contact"

    get 'users/auth/failure' do
      flash[:notice] = params[:message]
      redirect '/'
    end
    
    get 'home_search' => "rides#home_search"
  
  end

end

app/models/message.rb
class Message < ActiveRecord::Base
  
  belongs_to :user
    
  validates :content, :presence => true, :length => { :maximum => 1000 }
  validates :sujet, :presence => true, :length => { :maximum => 40 }
  email_regex = /^$|\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :sender_email, :format => { :with => email_regex }

  def sender
    u = User.where(:id => sender_id)
    if u.present?
      return u.first
    else
      nil
    end
  end
  
  def line_breaks
    content.split("\n")
  end
  
  def self.mutual_messages(user, sender)
    z = self.scoped
    x = z.where(:user_id => user, :sender_id => sender)
    y = z.where(:sender_id => user, :user_id => sender)
    # x + y
    z = (x + y).sort { |a,b| b.created_at <=> a.created_at }
  end
  
  def self.my_messages
    self.unread.order('created_at DESC')
  end
  
  def msg_time
    t = created_at.strftime("%b %d, %l:%M")
    t = t + ' am' if created_at.hour < 12
    t = t + ' pm' if created_at.hour >= 12
    t
  end
  
  def self.unread
    self.where(:read => false)
  end
  
  def self.sent(user)
    self.where(:sender_id => user.id).order('created_at DESC').limit(5)
  end
  
  def self.archived
    self.where(:read => true)
  end
  
  def reply_sujet
    unless sujet.split(":").first == "re"
      self.sujet = "re: " + self.sujet 
    else
      self.sujet = self.sujet
    end
  end
  
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  before_filter :current_user?, :except => [:new, :create]
  before_filter :authenticate_user!, :except => [:new, :create]

  def get_inbox
    if current_user 
      @messages = current_user.messages.order('created_at DESC').paginate(:page => params[:page], :per_page => 5).includes(:user)
      @messages_sent = Message.sent(current_user).order('created_at DESC').paginate(:page => params[:page], :per_page => 5).includes(:user)
    end
  end
  
  def index
    get_inbox
  end
  def sent
    @messages_sent_all = Message.sent(current_user).paginate(:page => params[:page], :per_page => 10)
    get_inbox
    render 'index'
  end
  def all
    @messages_all = Message.where(:user_id => current_user.id).paginate(:page => params[:page], :per_page => 10).order('created_at DESC')
    get_inbox
    render 'index'
  end
  
  def show
    get_inbox
    @message = Message.find(params[:id])
    if current_user
      @mutual_messages = Message.where('id <> ?', @message.id).includes(:user).mutual_messages(@message.user, @message.sender)
      @reply = current_user.messages.new 
    end
  end
  
  def reply
    get_inbox
    @reply = current_user.messages.new
  end
  
  def new
    get_inbox
    @user = User.find(params[:user_id])
    @message = @user.messages.new
    if params[:reply_from].present?
      @reply_from = Message.find(params[:reply_from])
      unless @reply_from.sujet.split(":").first == "re"
        @message.sujet = "re: " + @reply_from.sujet 
      else
        @message.sujet = @reply_from.sujet
      end
    end
    @message.sujet ||= params[:subject]
  end
  
  def create
    get_inbox
    @user = User.find(params[:user_id])
    @message = @user.messages.build(params[:message])
    @message.sender_id = current_user.id if current_user
    @message.read = false
    if @message.save
      MessageMailer.send_message(@message).deliver if @message.sender_id.present?
      MessageMailer.send_message_anon(@message).deliver if !@message.sender_id.present?
      flash[:notice] = "Message sent"
      redirect_to @message
    else
      render 'new'
    end
  end
  
  def update
    @message = Message.find(params[:id])
    if @message.update_attributes(params[:message])
      flash[:notice] = "done"
      redirect_to user_messages_path(current_user)
    else
      flash[:error] = "oops"
      redirect_to user_messages_path(current_user)
    end
  end
  
  def edit
    @message = Message.find(params[:id])
    @user = User.find(@message.user_id)
    get_inbox
  end
  
  def destroy
    Message.find(params[:id]).destroy
    redirect_to user_messages_path(current_user) 
  end

end

app/helpers/messages_helper.rb
module MessagesHelper
  
end

app/views/messages/_fields.html.erb
<table class="tble shadow"><tr><td>

	<%= simple_form_for msg do |f| %>
	  <%= f.input :sujet, :label => "subject:", :required => false %>
	  <%= f.input :content, :as => :text, :label => "message:" , :class => "text_area", :required => false %>
	  <%= f.submit "send", :class => "btn btn-primary" %>
	<% end %>


</table>

app/views/messages/_inbox.html.erb
<h3 class="heading">
<%= link_to "sent messages(#{@messages_sent.count})", user_sent_messages_path(current_user), :style => "color: #333;" %>
</h3> 
<div class="well">
 <% unless @messages_sent.empty? %>
   <% @messages_sent.each do |msg| %>
     <%= render 'messages/message_stubs', :msg => msg %>
   <% end %>
 <% else %>
   <br><h4 class="center"><i>no sent messages</i></h4><br>
 <% end %>
</div>


<h3 class="heading"><%= link_to "read messages (#{@messages.archived.count})", user_all_messages_path(current_user), :style => 'color: #333;' %></h3>
<div class="well">
  <% unless @messages.archived.empty? %>
    <% @messages.archived.each do |msg| %>
      <%= render 'messages/message_stubs', :msg => msg %>
    <% end %>
  <% else %>
  <br>
  <h4 class="center"><i>no archived messages</i></h4>
  <br>
<% end %>
</div>

app/views/messages/_message.html.erb
<tr> 
  <td class="">
    <div class="center">
	 <u><%= link_to ("#{msg.sender.username}  -->  #{msg.user.username} - #{msg.msg_time}"), msg %></u><br>

	<p class="well"><em><%= truncate(msg.content, :length => 40) %></em>
	</p>
	</div>
	<% if current_user == msg.sender || current_user == msg.user %>
    <% end %>
    </div>
  </td>
</tr>

app/views/messages/_message_stubs.html.erb
<ul style="margin: 0px 10px;">
  <li>
    <% if msg.sender.present? %>
      <b>
	  <%= gravatar_for msg.sender, :thumb, :size => 30 %>
	  <%= link_to msg.sender.username, msg.sender %>:
	  </b>
	<% else %>
	  <b><%= msg.sender_email.truncate(10) %>:</b>
	<% end %>
    <% if msg.sender != current_user && msg.read == false %><b><% end %>
	<%= link_to (msg.sujet ||= "subject"), msg %></b><br>
	<div class="alt"><%= msg.msg_time %></div>
  </li>
</ul>

app/views/messages/_reply.html.erb
<%= render 'fields' %>

app/views/messages/_show_message.html.erb
<table border=0 class="tble msg">
	<tr>
	<th class="top">from: </th>
	<td><% if msg.sender.present? %>
		  <%= gravatar_for msg.sender, :thumb, :size => 30 %> 
		  <%= link_to msg.sender.username, msg.sender %>
		<% else %>
		  <%= msg.sender_email %>
		<% end %><br>
	</td>
    </tr>

    <tr>
	<th>to: </th>
	<td>
	  <% if msg.user == current_user %>
	    <h4>You!</h4>
	  <% else %>
	    <%= gravatar_for msg.user, :thumb, :size => 30 %> <%= link_to msg.user.username, msg.user %>
	  <% end %>
	</td>
	</tr>
	
	<tr style="padding-top: 0px; vertical-align: bottom;">
	<th>subject: </th>
	<td style="padding-bottom: 5px;"><strong> <%= msg.sujet %></strong>
	</td>
	<td></td>
	<td style="padding-bottom: 3px; vertical-align: bottom;"><b>sent: </b><span class="alt"><%= msg.msg_time %></div>
	</tr>
	
	<tr>
	<th class="bottom">message: </th>
	<td colspan=3 class="msg" style="background-color: white;">
	  <% msg.line_breaks.each do |m| %>
	    <%= m %><br>
	  <% end %>
	</td>
    </tr>
  <tr>

  <% if msg.user == current_user %>
    <td></td>
    <td colspan=3 style="text-align: left;">
	  <% if msg.id == params[:id].to_i %>
	    <% msg.read = true %><% msg.save %>
	  <% end %>
    <%= form_for msg do |f| %>
      <% if msg.read == true %>
   	   	<%= f.hidden_field(:read, :value => false) %>
   	   	<%= f.submit "mark as unread", :class => "btn" %>
      <% else %>
        <%= f.hidden_field(:read, :value => true) %>
        <%= f.submit "mark as read", :class => "btn btn-primary" %>
	  <% end %>
    <% end %>
   

<!-- Reply field -->
<% if msg.sender.present? %>
<div class="accordion-heading">
  <a class="btn btn-primary accordion-toggle" data-toggle="collapse" href="#reply" style="float:left;">reply</a></tr>
</div>
    <tr><td colspan=4>
	<div id="reply" class="accordion-body collapse"><div class="well">
    <% @reply.sujet = msg.reply_sujet %>
    <div style="float:left; text-align:right; height: 30px; vertical-align: bottom; width:159px;"><b>to:</b></div>
<div style="float:left; padding-left: 12px;"><h4><%= msg.sender.username.titlecase %></h4></div><br><br>
<div style="clear:both;">
		<%= simple_form_for [msg.sender, @reply] do |f| %>
		  <%= f.input :sujet, :label => "subject:", :required => false %>
		  <%= f.input :content, :as => :text, :label => "message:" , :class => "text_area", :required => false %>
		  <%= f.submit "send", :class => "btn btn-primary", :style=> "float:right; margin-right: 120px;"%>
		<% end %>
</div>		
</div>
</div>
<% else %>
<p>This person does not have an account. Reply to their email if you find them believable.<br>
If this sounds like spam, please <%= link_to "report", contact_path %>!</p>	  
<% end %>
<!-- End reply -->


    </td>
  <% else %>
    <td style="text-align: right;">
    <%= link_to "edit", edit_message_path(msg), :class => "btn btn-warning" %>
    </td>
    <td>
    <%= link_to "delete", message_path(msg), :class => "btn btn-danger", :method => :delete  %>
    </td>
    </tr>
  <% end %>
  </div>
  </table>    
  

app/views/messages/edit.html.erb
<div class="hero-unit shadow-down"><h1>edit message</h1>
</div>


<div class="row">
  <div class="span8">
    <table class="tble msg"><tr><td>
	    <h4>
		  <span style="margin-left: 138px; margin-right: 8px;">to: </span>
		  <%= gravatar_for @user, :thumb, :size => 30 %> 
	      <%= link_to @user.username, @user %>
	    </h4><br>
    
	    <%= simple_form_for @message do |f| %>
	      <%= f.input :sujet, :label => "subject:", :required => false %>
	      <%= f.input :content, :as => :text, :label => "message:" , :class => "text_area", :required => false %>
	      <%= f.submit "send", :class => "btn btn-primary", :style => "margin-left: 170px;" %>
	    <% end %>
    </table>
  </div>
  <div class="span4">
    <%= render 'inbox' %>	
  </div>
</div>

app/views/messages/index.html.erb
<div class="hero-unit round">
  <h1>inbox</h1>
</div>

<div class="row">	
  <div class="span8"> 
  <% if params[:action] == 'index' %>
    <% msgs = @messages.unread %><% title = "unread messages(#{msgs.unread.count})"%>
  <% elsif params[:action] == 'all' %>
    <% msgs = @messages_all %><% title = "received messages" %>
  <% else %>
    <% msgs = @messages_sent_all %><% title = "sent messages" %>    
  <% end %>
    <h3 class="heading"><%= title %></h3>
    <div class="well">
    <% if msgs.count == 0 %>
	    <br>
        <h4 class="center"><i>no messages</i></h4>
        <br>
    <% else %>

      <% msgs.each do |msg| %>
	    <%= render 'message_stubs', :msg => msg %>
	  <% end %>
	  <%= will_paginate msgs, :class => "apple_pagination" %>
	
    <% end %>
    </div>
  </div>

  <div class="span4">
    <%= render 'inbox' %>	
  </div>

</div>

app/views/messages/new.html.erb
<div class="hero-unit shadow-down"><h1>write a message</h1>
</div>


<div class="row">
  <div class="span8">
    <table class="tble msg"><tr><td>
	    <h4>
		  <span style="margin-left: 138px; margin-right: 8px;">to: </span>
		  <%= gravatar_for @user, :thumb, :size => 30 %> 
	      <%= link_to @user.username, @user %>
	    </h4><br>
    
	    <%= simple_form_for [@user, @message] do |f| %>
	      <%= f.input :sujet, :label => "subject:", :required => false %>
	      <%= f.input :sender_email, :label => "from:", :placeholder => "(email)" if !current_user %>
	      <%= f.input :content, :as => :text, :label => "message:" , :class => "text_area", :required => false %>
	      <%= f.submit "send", :class => "btn btn-primary", :style => "margin-left: 170px;" %>
	    <% end %>
    </table>
    <% if @reply_from.present? %>
	  <%= render 'show_message', :msg => @reply_from %>
	<% end %>
  </div>
  <div class="span4">
    <%= render 'inbox' if current_user %>	
  </div>
</div>

app/views/messages/show.html.erb
<div class="hero-unit shadow-down">
  <h1>inbox</h1>
</div>

<div class="row"> 
  <div class="span8">
	<% if @message.sender == current_user %>
	  <h3 class="heading">sent message</h3>
	<% else %>
	  <h3 class="heading">message</h3>
	<% end %>
    <%= render 'show_message', :msg => @message %>
	<% if @message.sender.present? %>
	<% if @mutual_messages.count > 0 %>
      <br><br>	
      <h3 class="heading">other messages between you</h3> 
	  <div class="well">
	  <% @mutual_messages.each do |msg| %>
	    <%= render 'message_stubs', :msg => msg %>
	  <% end %>
	  </div>
	<% end %>
  <% end %>
  </div>

  <div class="span4">
    <%= render 'inbox' %>	
  </div>
</div>