config/routes.rb
Hithr::Application.routes.draw do
  
  constraints(subdomain: "blog") do
    resources :posts, :shallow => true do
      resources :comments
    end
    root :to => 'posts#index'
  end
  
  constraints(subdomain: !"blog" ) do
  
    match "rides/offered" => "rides#offered", :as => "rides_offered"
    match "rides/wanted" => "rides#wanted", :as => "rides_wanted"
    get "users/:user_id/rides" => "rides#user_rides", :as => "user_rides"
    get "/rides" => redirect("/rides/offered")
    match "rides/:id/return" => "rides#return", :as => "return_trip"
    resources :rides, :shallow => true do
      resources :details
    end
  
    resources :abouts, :except => [:destroy], :path => "/about"
  
    resources :authentications, :only => [:new, :create, :destroy]
    match 'users/auth/:provider/callback/' => 'authentications#create'
   
    devise_for :users, :controllers => {  :registrations => 'registrations', 
                                          :sessions => 'users/sessions', 
                                          :passwords => 'users/passwords' } do
      match "/sign_in" => "users/sessions#new"
      match "/sign_out" => "devise/sessions#destroy" 
      match "/sign_up" => "registrations#new" 
    end
  
    resources :users, :shallow => true do
      resources :messages
      resources :profiles
      resources :references
    end
    get 'users/:user_id/messages/sent' => 'messages#sent', :as => "user_sent_messages"
    get 'users/:user_id/messages/all' => 'messages#all', :as => "user_all_messages"
  
  
    root :to => 'pages#home'
    get "/contact" => "pages#contact"
    get "/help" => "pages#help"
    get "/test" => "pages#test"
    get "/send_contact" => "pages#send_contact", :as => "send_contact"

    get 'users/auth/failure' do
      flash[:notice] = params[:message]
      redirect '/'
    end
    
    get 'home_search' => "rides#home_search"
  
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :authentications,  :dependent => :destroy
  has_many :messages,         :dependent => :destroy
  has_one  :profile,          :dependent => :destroy
  has_many :references,       :dependent => :destroy
  has_many :rides,            :dependent => :destroy
  has_many :comments,         :dependent => :destroy
  
  after_save  :initialize_profile
  before_save :titleize_name
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and 
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable
  validates :firstname, :presence => true
  validates :lastname, :presence => true
  validates :email, :presence => true, :uniqueness => true

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :firstname, :lastname, :password, :password_confirmation, :remember_me
  
  
  def self.find_for_facebook_oauth(access_token, signed_in_resource=nil)
    data = access_token.extra.raw_info
    if user = User.where(:email => data.email).first
      user
    # else # Create a user with a stub password. 
    #       screen_name = data.email.split('@').first
    #       if User.where(:screen_name => screen_name).empty?
    #         User.new(:omniauth_facebook => true, :screen_name => screen_name, :email => data.email, :password => Devise.friendly_token[0,20]) 
    #       else
    #         screen_name = screen_name + '.2'
    #         User.new(:omniauth_facebook => true, :screen_name => screen_name, :email => data.email, :password => Devise.friendly_token[0,20]) 
    #       end
    end
  end
  
  
  def initialize_profile
    profile = Profile.find_or_create_by_user_id(:user_id => id)
    profile.cred ||= 0
    profile.about ||= ""
    profile.save
  end
  
  def build_auth(auth)
    authentications.build(:provider => auth['provider'], :uid => auth['uid'], :nickname => auth['info'].nickname)
  end
  
  def username
    "#{firstname} #{lastname.to(0)}"
  end
  
  def titleize_name
    self.firstname = self.firstname.titleize
    self.lastname = self.lastname.titleize  
  end
  
  def self.search(search)
    if search
      where('firstname LIKE ?', "%#{search.titleize}%")
    else
      scoped
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    render :text => request.env[omniauth.auth].to_yaml 
  end
  
  def google_oauth2
    render :text => request.env[omniauth.auth].to_yaml 
  end
  # def facebook
  #     @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)
  #       if @user.save
  #         flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Facebook"
  #         sign_in_and_redirect @user, :event => :authentication
  #       else
  #         # session["devise.facebook_data"] = @user
  #         redirect_to new_user_registration_path # (@user)
  #       end
  #   end



end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController


  def new
    
  end 
  
  
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController

  def new
    resource = build_resource
    clean_up_passwords(resource)
    respond_with(resource, serialize_options(resource))
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 
  respond_to :html, :json
  
  before_filter :authenticate_user!, :only => [:edit, :update, :destroy]
  before_filter :current_user?, :except => [:new, :create, :show]
  # before_filter :admin_index, :only => [:index]
  
  helper_method :sort_column, :sort_direction  

  def admin_index
    unless admin?
      flash[:notice] = "you do not have access."
      redirect_to root_path
    end
  end
  
  def index
    if params[:name_search].present?
      @users = User.search(params[:name_search])
    else
      @users = User.scoped
    end
      @users = @users.order(sort_column + ' ' + sort_direction).paginate(:page => params[:page], :per_page => 10)
  end
  
  def show
    @user = User.find(params[:id])
    @mutual_messages = Message.order('created_at DESC').limit(5).mutual_messages(@user, current_user)
  end
  
  def new
    
    
  end
  
  def create
  end
  
  def edit_fields
    
  end
  
  def update
    @user = User.find(params[:id])
    @user.update_attributes(params[:user])
    respond_with @user
  end
  
  def destroy
  end
  
  private
  
  def sort_column
    User.column_names.include?(params[:sort]) ? params[:sort] : "firstname"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
  
  def twitter_link
    "http://www.twitter.com/" + @user.authentications.where(:provider => "twitter").first.nickname
  end
  
  def facebook_link
    "http://www.facebook.com/" + @user.authentications.where(:provider => "facebook").first.uid
  end
  
  def google_link
    "http://www.google.com"
  end
  
  def auth_link(auth)
    return "http://www.twitter.com/" + @user.authentications.where(:provider => "twitter").first.nickname if auth.provider == "twitter"
    return "http://www.facebook.com/" + @user.authentications.where(:provider => "facebook").first.uid if auth.provider == "facebook"
    return "https://plus.google.com/" + @user.authentications.where(:provider => "google_oauth2").first.uid if auth.provider == "google_oauth2"
  end

  def cred_magic
    cred = @user.profile.cred
    cred += 1 if @user.profile.avatar_file_name.present?
    cred += 1 if @user.profile.about.length > 20
    cred += 1 if @user.profile.hometown.present?
    cred
  end

end

app/views/users/_index_table.html.erb
<table class="users_index" style="margin-left:5%;">
	<thead>
		<th style="width: 100px;">						<%= sortable "id", "id" %>  						</th>
		<th style="width: 150px; text-align:center;">	<%= sortable "firstname", "username" %> 		 	</th>
		<th style="width: 150px; text-align:center;">				  ride count							</th>
		<th style="width: 400px; text-align:center;">	<%= sortable "current_sign_in_at", "last sign in" %>  	</th>
	</thead>
	<tbody>
<% @users.each do |user| %>
	<tr>
		<td style="text-align: center;"><%= user.id %></td>
		<td style="padding-left: 2.2em;"><%= link_to user.username, user %></td> 
		<td style="text-align: center;"><%= user.rides.size %></td>
		<td style="text-align: center;"><%= user.current_sign_in_at.strftime("%b %d '%y at %I:%M %P") %></td>
	</tr>
<% end %>
</table>

<%= will_paginate @users, :class => "apple_pagination" %>

app/views/users/_mutual_messages.html.erb
<h3 class="heading">messages between you (<%= @mutual_messages.count %>)</h3>
<div class="well" style="margin-bottom:0px;">
<div class="center"><%= link_to "send them a message", new_user_message_path(@user), :class => "btn btn-primary" %></div>
<br>
<% if @mutual_messages.present? %>
	<% @mutual_messages.each do |msg| %>
	  <%= render 'messages/message_stubs', :msg => msg %>
	<% end %>	
	<% end %>
</div>

app/views/users/_my_messages.html.erb
<h3 class="heading top">
<%= link_to "unread messages (#{current_user.messages.unread.count})", user_messages_path(current_user) %>
</h3>
<div class="well bottom" style="margin-bottom:0px;">
<% if current_user.messages.my_messages.present? %>
	<% current_user.messages.my_messages.each do |msg| %>
	  <%= render 'messages/message_stubs', :msg => msg %>
	<% end %>
<% else %>
<div class="center"><%= link_to "go to inbox", user_messages_path(@user), :class => "btn btn-primary" %></div>
<% end %>
</div>

app/views/users/_my_references.html.erb
<div class="heading top">
<h3 class="">references (<%= @user.references.count %>)</h3>
<p>	Positive (<%= @user.references.positive_refs.count %>) | 
	Neutral (<%= @user.references.neutral_refs.count %>) |
	Negative (<%= @user.references.negative_refs.count %>)
	
</div>
<div class="well bottom">
<% if @user != current_user %>
<div class="center">
<%= link_to "leave a reference", new_user_reference_path(@user), :class => "btn btn-primary	" %>
</div><br>
<% end %>
<% if @user.references.present? %>
  <%= render 'references/reference' %>
<% else %>
<h4 class="center"><i>no references<i></h4>
<% end %>
</div>

app/views/users/edit_fields.html.erb
<h2>sign up</h2>
<p>Please complete the fields below to complete your registration.</p>

<%= form_for @user%>

app/views/users/index.html.erb
<div class="hero-unit">
<h1>users</h1>
</div>
<div class="super-small-container">
	<br>
	<div class="center">
	<p>Search by first names:</p>
	<%= form_tag users_path, :method => :get, :id => "name_search" do %>
	  <%= hidden_field_tag :direction, params[:direction] %>
	  <%= hidden_field_tag :sort, params[:sort] %>
	  <%= text_field_tag :name_search, params[:name_search] %>
	  <%= submit_tag "submit"%>
	<% end %>
	<% link_to "all users", users_path %>
	</div>

<div id="index_table">
<%= render 'index_table'%>
</div>
<br>
</div>

app/views/users/index.js.erb
$('#index_table').html("<%= escape_javascript(render("index_table")) %>");

app/views/users/show.html.erb
<div class="row">
	
<div class="span8">
  
<div class="hero-unit" style="margin: 0 0px 0 0px; height: auto;">
		
<!-- cred -->
      <div style="float:right; margin: 22px 0px 0 20px; height:106px;"><div class="cred round">
	    cred: <%= cred_magic %>
	  </div></div>
	
<!-- photo -->
      <div style="float: left;">
        <%= link_to (gravatar_for @user, :small, :size => 100), avatar_medium %>
      </div>
        <% if @user == current_user %>
      <div style="clear:left;">
		  <a class="accordion-toggle" data-toggle="collapse" data-parent="#acc" href="#edit-photo">edit photo</a>
		  <div id="edit-photo" class="accordion-body collapse" style="clear:both;">
		  <%= form_for current_user.profile do |f| %>
		    <%= f.file_field :avatar, :label => nil %><br>
			<%= f.submit "upload", :class=>"btn btn-primary" %>
		  <% end %>
		</div> 
		</div>
		<% end %>
		
<!-- name/auth	 -->	
	  <h1 style="clear:left; font-size:3em;"><%= @user.username %></h1>
	  <% if @user.authentications.present? %>
	  
        <% @user.authentications.each do |auth| %>
          <%= link_to (image_tag "#{auth.provider}_32.png"), auth_link(auth), :class => "auth_provider" if current_user %>
 	      <%= image_tag "#{auth.provider}_32.png" if !current_user %>
	    <% end %>
	  <% end %>
	  <% if @user.rides.count > 0 %>
	    <br>
		<%= link_to "#{pluralize(@user.rides.count, "posted ride")}.", user_rides_path(@user) %>
	  <% end %>

</div><!-- end of hero-unit -->

  <div class="well" style="margin-bottom: 0px;">
      <% if @user == current_user %>
        <div class="center">
          <a class="accordion-toggle" data-toggle="collapse" href="#edit-profile">edit public profile</a>
		</div>
        <div id="edit-profile" class="accordion-body collapse" style="clear:both;">
        <div class="well">
        <%= simple_form_for current_user.profile do |f| %>
          <div class="control-group select">
          <%= f.label :birthday, "birthday:" %>
  		  <% bd = @user.profile.birthday %><% bd ||= Date.today %><% bd = bd.change(:year => 1980) %>
          <%= f.date_select(:birthday, :order => [:month, :day, :year], :start_year => 1940, :end_year => 1994, :default => bd) %>
          </div><% gen = @user.profile.gender %><% gen ||= "human" %>
          <%= f.input 	:gender, :label => "gender:", 
 						:collection => [["traveller"], ["woman"], ["human"], ["man"], ["zombie"]], :selected => gen %>
          <%= f.input :hometown, :label => "current city:" %>
          <div class="center"><%= f.submit "update", :class=>"btn btn-primary" %></div>
        <% end %>
        </div>
        </div>
      <% end %>
      <div class="profile round" style="font-size:110%; padding: 20px;">
        <div class="left"><b>age: </b></div>
        <div class="right"><%= distance_in_years(@user.profile.birthday) if @user.profile.birthday.present? %></div><br>
        <div class="left"><b>gender: </b></div>
        <div class="right"><%= @user.profile.gender if @user.profile.gender.present? %></div> <br>
        <div class="left"><b>current city: </b></div>
        <div><%= @user.profile.hometown if @user.profile.hometown.present? %></div><br>
      </div>
              	   
	  <div class="profile round" style="padding:20px;">
        <div class="round shadow bio" style="">bio: </div>
        <div class="about content" style="">
	    <p>
		    <% @user.profile.about = nil if @user.profile.about == "" %>
		    <% @user.profile.about ||= "click here to create a bio" if @user == current_user %>
		    <% @user.profile.about ||= "this person has not filled out a bio yet" if @user != current_user %>
		    <%= best_in_place_if @user == current_user, @user.profile, :about, :type => :textarea %>
		</p>
        </div>
      </div><br><br>
    </div>
     
		<% if @user == current_user %>
		  <h3 class="heading top">private profile</h3>
	      <div class="well bottom">
		    <b>private profile:</b>
		    <%= link_to "(edit)", edit_user_registration_path(@user) %><br>
		    <strong>name: </strong><%= "#{@user.firstname} #{@user.lastname}" %><br>
		    <strong>email: </strong><%= best_in_place @user, :email %><br>
		    <strong>birthday: </strong><%= @user.profile.birthday.strftime("%B %e, %Y") if @user.profile.birthday.present? %><br>
		    <br>
		    <%= render 'layouts/create_authentications' %>
		  </div>
		<% else #not current_user %>
		<% end %>
	</div>
	<div class="span4">
   		  <% if current_user %>
		      <% if @user == current_user %>
		        <%= render 'my_messages', :user => @user %>
		      <% else %>
		  	    <%= render 'mutual_messages', :user => @user %>
		      <% end %>
		  <% end %>
		    <%= render 'my_references', :user => @user %>
	</div>



</div>