config/routes.rb
Hithr::Application.routes.draw do
  
  constraints(subdomain: "blog") do
    resources :posts, :shallow => true do
      resources :comments
    end
    root :to => 'posts#index'
  end
  
  constraints(subdomain: !"blog" ) do
  
    match "rides/offered" => "rides#offered", :as => "rides_offered"
    match "rides/wanted" => "rides#wanted", :as => "rides_wanted"
    get "users/:user_id/rides" => "rides#user_rides", :as => "user_rides"
    get "/rides" => redirect("/rides/offered")
    match "rides/:id/return" => "rides#return", :as => "return_trip"
    resources :rides, :shallow => true do
      resources :details
    end
  
    resources :abouts, :except => [:destroy], :path => "/about"
  
    resources :authentications, :only => [:new, :create, :destroy]
    match 'users/auth/:provider/callback/' => 'authentications#create'
   
    devise_for :users, :controllers => {  :registrations => 'registrations', 
                                          :sessions => 'users/sessions', 
                                          :passwords => 'users/passwords' } do
      match "/sign_in" => "users/sessions#new"
      match "/sign_out" => "devise/sessions#destroy" 
      match "/sign_up" => "registrations#new" 
    end
  
    resources :users, :shallow => true do
      resources :messages
      resources :profiles
      resources :references
    end
    get 'users/:user_id/messages/sent' => 'messages#sent', :as => "user_sent_messages"
    get 'users/:user_id/messages/all' => 'messages#all', :as => "user_all_messages"
  
  
    root :to => 'pages#home'
    get "/contact" => "pages#contact"
    get "/help" => "pages#help"
    get "/test" => "pages#test"
    get "/send_contact" => "pages#send_contact", :as => "send_contact"

    get 'users/auth/failure' do
      flash[:notice] = params[:message]
      redirect '/'
    end
    
    get 'home_search' => "rides#home_search"
  
  end

end

app/views/shared/_alerts.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
    <a class="close" data-dismiss="alert">×</a>
    <%= msg.downcase %>
  </div>
<% end %>

app/views/shared/_blog_navbar.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
	<div class="container">
		
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
	  <%= link_to "blog.hithr.to", root_url(subdomain: "blog"), :class => "brand", 
				:style => "text-decoration: none; margin-left:80px;" %>
      <div class="nav-collapse">
        <ul class="nav nav-pills">
          <li class="divider-vertical"></li>
        <% if current_user == admin %>
		  <li><%= link_to "new post", new_post_url %></li>
		  <% end %>
          <li><%= link_to "hithr.to", root_url(subdomain: false) %></li> 
  
          <li><%= link_to "about", abouts_url(subdomain: false) %></li>
          <li><%= link_to "contact", contact_url(subdomain: false) %></li>
        </ul>
      </div>
	  <div class="nav-collapse" style="float:right; margin-right:80px;">
		
	    <ul class="nav nav-pills">
	      <% if current_user %>
		    <% if current_user.messages.unread.count > 0 %>
		      <li><%= link_to "#{pluralize(current_user.messages.unread.count, 'unread message')}", message_path(current_user.messages.unread.first) %>
			  </li>
			<% end %>
		  
	      <li class="dropdown">
		  
	        <a class="dropdown-toggle" data-toggle="dropdown">
		    <%= current_user.username %>
			
	           <b class="caret"></b></a>
	        <ul class="dropdown-menu">
		      <li><%= link_to "messages", user_messages_url(current_user, subdomain: false) %></li> 
		      <li><%= link_to "my rides", user_rides_url(current_user, subdomain: false) %></li>
		      <li><%= link_to "see profile", user_url(current_user, subdomain: false) %></li>
		      <li><%= link_to "sign out", sign_out_url(subdomain: false) %></li>  
		    </ul>
		  </li>
	    
	      <% else %>
	      <li><%= link_to "sign up", sign_up_url(subdomain: false) %></li>
	      <li><%= link_to "sign in", sign_in_url(subdomain: false) %></li> 
	      <% end %>
	        
	    </ul>
	  </div>
	  <div style="float:right;">
		<%= render 'shared/alerts' %>
	</div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_city_search.html.erb
<div class="content round" style="height: 30px; margin-bottom: 0px;">
  <div class="small-container" style="padding: 0 32% 0 32%;">
    <div id="city_search">		
      <%= form_tag rides_offered_path, :method => 'get', :class => "form-search" do %>
	    <% loc = request.location %>
		<% seed_city = loc.city if loc.present? %>
		<% seed_city ||= "" %>
		<label style="width: auto;">Start city:</label>
		<%= text_field_tag :search_start, seed_city, 
		                                          :placeholder => "(city, state)", :style => "width: 100px;" %> 
		<%= hidden_field_tag :search_date %>
		<%= submit_tag "search", :name => nil, :class => "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if @detail.errors.any? %>

  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> 
        prohibited this <%= object.class.to_s.underscore.humanize.downcase %> 
        from being saved:</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_links.html.erb
<%- if devise_mapping.registerable? && controller_name != 'registrations' %>or<br>
  <%= link_to "sign up", new_registration_path(resource_name), :class => "btn" %>
<% end -%>

<%- if controller_name != 'sessions' %><br>or <br>
  <%= link_to "sign in", new_session_path(resource_name), :class => "btn" %>
<% end -%><br /><br>
<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "forgotten password?", new_password_path(resource_name), :style => "font-size: .8em;" %><br /><br>
<% end -%>

<%- if devise_mapping.omniauthable? %>
   <h3>or connect with:</h3>
  <%- resource_class.omniauth_providers.each do |provider| %>
   
    <%= link_to (image_tag "#{provider}_64.png"), omniauth_authorize_path(resource_name, provider), :class => "auth_provider" %>
    <% link_to "#{provider.to_s.split('_').first}", omniauth_authorize_path(resource_name, provider) %>
  <% end -%>
<% end -%>
<br><br>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

app/views/shared/_messages.html.erb
<% @user.messages.each do |msg| %>
  ERROR<% render 'messages/message', :msg => msg %>
<% end %>

app/views/shared/_mutual_messages.html.erb
<tr><td class="center"><h3>- messages between you (<%= @mutual_messages.count %>) -</h3><br>

<%= link_to "send them a message", new_user_message_path(@user), :class => "btn btn-primary" %></td></tr>
<br><br>
<% if !@mutual_messages.empty? %>
	<% @mutual_messages.each do |msg| %>
	  <%= render 'messages/message', :msg => msg %>
	<% end %>	
<% end %>

app/views/shared/_my_messages.html.erb
<tr>
	<td class="center"><h3>- unread messages (<%= @user.messages.unread.count %>) -</h3><br></td>
</tr>
<% if @user.messages.present? %>
	<% current_user.messages.my_messages.each do |msg| %>
	  <%= render 'messages/message', :msg => msg %>
	<% end %>
<% else %>
<tr><td class="center">you have no messages<br>
<%= link_to "see all messages", user_messages_path(@user) %><br></tr>
<% end %>

app/views/shared/_my_references.html.erb
<tr><td class="center"><h3>- references (<%= @user.references.count %>) -</h3>
<% if @user != current_user %>
<br><%= link_to "leave a reference", new_user_reference_path(@user), :class => "btn btn-primary	" %><br><br>
</td></tr>
<% end %>
<% if @user.references.present? %>
  <%= render 'references/reference' %>
<% else %>
  <tr><td class="center block">no references</tr>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
	<div class="container">
		
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to "hithr.to", root_path, :class => "brand", :id => "nav_brand", 
				:style => "text-decoration: none; margin-left:80px;" if request.subdomain != "blog" %>
	  <%= link_to "blog.hithr.to", root_url(subdomain: "blog"), :class => "brand", 
				:style => "text-decoration: none; margin-left:80px;" if request.subdomain == "blog" %>
      <div class="nav-collapse">
        <ul class="nav nav-pills">
          <li class="divider-vertical"></li>
		<li class="dropdown">
			<a class="dropdown-toggle" data-toggle="dropdown">rides <b class="caret"></b></a>
			<ul class="dropdown-menu">
			  <li><%= link_to "post ride", new_ride_path %></li>
              <li id="nav_ride_offered"><%= link_to "rides offered", rides_offered_path %></li>
 			  <li id="nav_ride_wanted"><%= link_to "rides wanted", rides_wanted_path %></li>
			</ul>
		</li>
          <li id="navbar_about_link"><%= link_to "about", abouts_path %></li> 
          <li><%= link_to "blog", root_url(subdomain: "blog") %>
          <li><%= link_to "contact", contact_path %></li>
          <li><% link_to  "help", help_path %></li>
        </ul>
      </div>
	  <div class="nav-collapse" style="float:right; margin-right:80px;">
		
	    <ul class="nav nav-pills">
	      <% if signed_in? %>
		    <% if current_user.messages.unread.count > 0 %>
		      <li><%= link_to "#{pluralize(current_user.messages.unread.count, 'unread message')}", message_path(current_user.messages.unread.first) %>
			  </li>
			<% end %>
		  
	      <li class="dropdown">
		  
	        <a class="dropdown-toggle" data-toggle="dropdown">
		    <%= current_user.username %>
			
	           <b class="caret"></b></a>
	        <ul class="dropdown-menu">
		      <li><%= link_to "messages", user_messages_path(current_user) %></li> 
		      <li id="user_rides_link"><%= link_to "my rides", user_rides_path(current_user) %></li>
		      <li><%= link_to "profile", current_user %></li>
		      <li><%= link_to "sign out", sign_out_path %></li>  
		    </ul>
		  </li>
	    
	      <% else %>
	      <li><%= link_to "sign up", sign_up_path %></li>
	      <li><%= link_to "sign in", sign_in_path %></li> 
	      <% end %>
	        
	    </ul>
	    </div>
		  <div style="float:right;">
			<%= render 'shared/alerts' %>
		</div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_ride_search.html.erb
<table style="width:100%;">
<tr>	<th colspan=2> </th>
	<th> On <% link_to "On", "#" %> </th>
	<th colspan=1> From <% link_to "From", "#" %> </th>
	<th> </th>
	<th colspan=1> To <% link_to "To", "#" %> </th>
    <th class="ride_hide_small"> </th>
</tr>
</thead>	
<tr>
  <% path = rides_offered_path if params[:action] == 'offered' %>
  <% path = rides_wanted_path if params[:action] == 'wanted' %>
  <% path = user_rides_path(User.find(params[:user_id])) if params[:action] == 'user_rides' %>

<%= form_tag path, :method => 'get', :class => "form-search", :id => "ride_search" do %>

	<td colspan="2">  
	  <%= select_tag(:miles_radius, 
			options_for_select([['search radius', 0], ['10 miles', 10], 
								['20 miles', 20], ['30 miles', 30], 
								['40 miles', 40]], params[:miles_radius]), :class => "auto") %>
	</td>
	
	<td class="date">
	  <% @search_date = get_search_date %>
	  <%= select_date @search_date, {:order => [:month, :day], :use_short_month => true} %>
	</td>

	<td colspan="2">
	  <% loc = request.location %>
	  <% seed_city = params[:search_start] %>
	  <% seed_city ||= loc.city if loc.present? %>
	  <%= text_field_tag :search_start, params[:search_start], 
	                                          :placeholder => "(city, state)", :class => "" %>
	</td>
	
	<td>					
	  <%= text_field_tag 	:search_end,
	                   		params[:search_end],
	                  		:placeholder => "(optional)", :class => "" %>
	</td>

	<td colspan=1 class="ride_hide_small">
	  <%= submit_tag "Search", :name => nil, :class => "btn btn-primary" %>
	</td>
	</tr>
	<tr class="ride_show_small">
		<td colspan=6 class="center"><%= submit_tag "Search", :name => nil, :class => "btn btn-primary" %></td>
	</tr>
<% end %>
</table>