config/routes.rb
Hithr::Application.routes.draw do
  
  constraints(subdomain: "blog") do
    resources :posts, :shallow => true do
      resources :comments
    end
    root :to => 'posts#index'
  end
  
  constraints(subdomain: !"blog" ) do
  
    match "rides/offered" => "rides#offered", :as => "rides_offered"
    match "rides/wanted" => "rides#wanted", :as => "rides_wanted"
    get "users/:user_id/rides" => "rides#user_rides", :as => "user_rides"
    get "/rides" => redirect("/rides/offered")
    match "rides/:id/return" => "rides#return", :as => "return_trip"
    resources :rides, :shallow => true do
      resources :details
    end
  
    resources :abouts, :except => [:destroy], :path => "/about"
  
    resources :authentications, :only => [:new, :create, :destroy]
    match 'users/auth/:provider/callback/' => 'authentications#create'
   
    devise_for :users, :controllers => {  :registrations => 'registrations', 
                                          :sessions => 'users/sessions', 
                                          :passwords => 'users/passwords' } do
      match "/sign_in" => "users/sessions#new"
      match "/sign_out" => "devise/sessions#destroy" 
      match "/sign_up" => "registrations#new" 
    end
  
    resources :users, :shallow => true do
      resources :messages
      resources :profiles
      resources :references
    end
    get 'users/:user_id/messages/sent' => 'messages#sent', :as => "user_sent_messages"
    get 'users/:user_id/messages/all' => 'messages#all', :as => "user_all_messages"
  
  
    root :to => 'pages#home'
    get "/contact" => "pages#contact"
    get "/help" => "pages#help"
    get "/test" => "pages#test"
    get "/send_contact" => "pages#send_contact", :as => "send_contact"

    get 'users/auth/failure' do
      flash[:notice] = params[:message]
      redirect '/'
    end
    
    get 'home_search' => "rides#home_search"
  
  end

end

app/models/ride.rb
class Ride < ActiveRecord::Base
  
  belongs_to :user
  has_one :detail, :dependent => :destroy
  attr_accessor :go_time_hour, :go_time_min
  
  validates_presence_of :user_id, :start_city, :start_state, :end_city, :end_state, 
                        :go_time, :latitude, :longitude, :end_lat, :end_long
  validates :start_city,  :length => { :maximum => 20 }
  validates :end_city,    :length => { :maximum => 20 }
  
  before_validation :before_save_events
  
  
  def before_save_events
   unless self.start_city == "" || self.end_city == ""
      find_or_create_cities
      get_distance
      get_your_bearings
    end
  end
  
  geocoded_by :start_city_state
  
  def find_or_create_cities
    s = find_or_create_city(self.start_city, self.start_state)
    e = find_or_create_city(self.end_city, self.end_state)
    self.start_city = s.name.split(', ').first
    self.start_state = s.name.split(', ').last
    self.end_city = e.name.split(', ').first
    self.end_state = e.name.split(', ').last
    self.latitude = s.lat
    self.longitude = s.long
    self.end_lat = e.lat
    self.end_long = e.long
  end
  def find_or_create_city(city, state)
    City.find_or_create_by_name("#{city.try(:titleize).try(:strip)}, #{state.try(:upcase).try(:strip)}") 
  end
  
  def get_lat_long_both
    lat_long = get_lat_long(self.start_city, self.start_state)
    self.latitude = lat_long.first
    self.longitude = lat_long.last
    end_lat_long = get_lat_long(self.end_city, self.end_state)
    self.end_lat = end_lat_long.first
    self.end_long = end_lat_long.last
  end
  
  def get_lat_long(city, state)
    city_state = city + ", " + state
    c = City.find_or_create_by_name(city_state)
    # unless city = City.where(:name => city_state)
    #    city = City.new
    #    city.name = city_state
    #    city.save
    #  end
    return [c.lat, c.long]
  end
  
  
  def start_city_state
    "#{start_city}, #{start_state}"
  end 
  
  def get_user_ip
    user_location = Geocoder.request
  end
  
  def get_your_bearings
    # dest = end_city + ', ' + end_state
    # destcoords = Geocoder.coordinates(dest)
    self.bearing = Geocoder::Calculations.bearing_between([latitude, longitude], [end_lat, end_long])
  end
  
  def get_distance
    crow_flies = Geocoder::Calculations.distance_between([latitude, longitude], [end_lat, end_long])
    self.trip_distance = ((crow_flies / 100 * 1.12).round(0)) * 100
  end
  
  # SEARCH(es)
  
  def self.search(criteria)
    @rides = Ride.where("go_time > ?", criteria[:search_date]).includes(:user)
    if criteria[:search_start_city].present?
      if criteria[:miles_radius].to_i == 0 
        rides = @rides.search_start(criteria[:search_start_city], criteria[:search_start_state])
        if rides.count < 1
          criteria[:miles_radius] = 20
        else
          @rides = rides
        end
      end 
      if criteria[:miles_radius].to_i > 1
       rides = @rides.search_near(criteria[:search_start_city], criteria[:search_start_state], criteria[:miles_radius])
        # if rides.count < 5
          # criteria[:miles_radius] += 10
          # @rides = @rides.search_near(criteria[:search_start_city], criteria[:search_start_state], criteria[:miles_radius])
        #else
          @rides = rides
        # end
      end
    end
    unless @rides.empty?
      if criteria[:search_end_city].present?
        rides_dest = @rides.search_destination(criteria[:search_end_city], criteria[:search_end_state])
        if rides_dest.count < 1
         if criteria[:search_start_city].present?
            @rides = @rides.search_direction(criteria)
          else
            @rides = @rides.search_near(criteria[:search_end_city], criteria[:search_end_state], 20)
          end
        else
          @rides = rides_dest
        end
      end
    end
    @rides
  end  
    
  def self.search_start(city, state)
    if state.present?
      rides = @rides.where(:start_state => state)
    end
    if city.present?
      rides ||= @rides
      rides = rides.where("start_city LIKE ?", "%#{city}%")
    end
    rides
  end
  
  def self.search_destination(city, state)
    if state.present?
      rides_dest = @rides.where(:end_state => state)
    end
    if city.present?
      rides_dest ||= @rides
      rides_dest = rides_dest.where("end_city LIKE ?", "%#{city}")
    end
  end
  
  def self.search_near(city, state, radius)
    near("#{city}, #{state}", radius)
  end
  
  def self.search_direction(criteria)
    search_bearing = Geocoder::Calculations.bearing_between("#{criteria[:search_start_city]}, #{criteria[:search_start_state]}", 
                                                            "#{criteria[:search_end_city]}, #{criteria[:search_end_state]}")
    @rides.where(:bearing => (search_bearing - 20)..(search_bearing + 20))
  end 
  
end

app/controllers/rides_controller.rb
class RidesController < ApplicationController

  before_filter :authenticate_user!, :only => [:edit, :update, :destroy]
  before_filter :current_user?, :except => [:offered, :show, :wanted, :user, :home_search]
  respond_to :html, :json
 
  def offered
    # sleep 1
    @rides = Ride.where(:offered => true).search(make_criteria).reorder('go_time ASC')
    @rides = @rides.paginate(:page => params[:page], :per_page => 10)# .includes(:user)
    if @rides.blank?
      flash.now[:notice] = "Sorry. Try increasing the search radius."    
    end
    render 'index'
  end
  
  def wanted
    @rides = Ride.where(:offered => false).search(make_criteria).reorder('go_time ASC')
    @rides = @rides.paginate(:page => params[:page], :per_page => 10) #.includes(:user)
    if @rides.blank?
      flash.now[:notice] = "Sorry. Try increasing the search radius."
    end
    render 'index'
  end
   
  def user_rides
    @user = User.find(params[:user_id])
    @rides = @user.rides.search(make_criteria).reorder('go_time ASC')
    @rides = @rides.paginate(:page => params[:page], :per_page => 10)
    render 'index'
  end 
  
  def show
    @ride = Ride.find(params[:id])
    @ride.detail ||= Detail.new
    respond_to do |format|
      format.html
      format.json { render json: @ride }
    end
  end
  
  def new
    @ride = Ride.new
    loc = get_user_ip
    @ride.start_city = loc.city if loc.present?
    @ride.start_state = loc.state_code if loc.present?
    @ride.go_time = Date.tomorrow + 9.hours
  end
  
  def create
    @ride = current_user.rides.build(params[:ride])
    @ride.go_time = @ride.go_time.change(:hour => params[:ride][:go_time_hour], :min => params[:ride][:go_time_min])
    if @ride.save
      flash[:notice] = "ride posted!"
      @ride.detail = Detail.create(:cost => (@ride.trip_distance / 10), 
                                    :seats_available => "1", :radio => "Flexible", 
                                    :bikes => 0, :smoking => 0)
      redirect_to @ride
    else
      flash[:notice] = "something went wrong :("
      render 'new'
    end
  end
  
  def edit
    @ride = Ride.find(params[:id])
  end 
  
  def update
    @ride = Ride.find(params[:id])
    @ride.update_attributes(params[:ride])
    @ride.go_time = @ride.go_time.change(:hour => params[:ride][:go_time_hour], :min => params[:ride][:go_time_min])
    @ride.save
    @ride.detail.update_attributes(:cost => @ride.trip_distance / 10)
    respond_with @ride
  end
  
  def destroy
    @ride = Ride.find(params[:id])
    @ride.destroy
    respond_to do |format|
      format.html { redirect_to rides_url }
      format.json { head :no_content }
    end
  end
  
  def return
    @ride = Ride.find(params[:id])
    go_time = @ride.go_time
    day = go_time.day + 2
    go_time = go_time.change(:day => day)
    return_trip = current_user.rides.build( :start_city => @ride.end_city, :start_state => @ride.end_state,
                        :end_city => @ride.start_city, :end_state => @ride.start_state,
                        :go_time => go_time)
    return_trip.save
    return_trip.detail = Detail.create(:cost => (return_trip.trip_distance / 10), 
                                  :seats_available => @ride.detail.seats_available, :radio => @ride.detail.radio, 
                                  :bikes => @ride.detail.bikes, :smoking => @ride.detail.smoking)
    @ride = return_trip
    redirect_to edit_ride_path(@ride)
  end
  
  def home_search
    
  end
  
  def make_criteria
    criteria = {}
    if params[:date].present?
      search_date = make_date
    end
    criteria[:search_date] = search_date ||= Date.today
    if params[:search_end].present?
      criteria[:search_end_city] = get_city(params[:search_end])
      criteria[:search_end_state] = get_state(params[:search_end])
    end
    if params[:search_start].present?      
      criteria[:search_start_city] = get_city(params[:search_start])
      criteria[:search_start_state] = get_state(params[:search_start])
    end
    criteria[:miles_radius] = params[:miles_radius].to_i ||= 0
    criteria
  end
   
  def make_date
    Date.civil(params[:date][:year].to_i, params[:date][:month].to_i, params[:date][:day].to_i)
  end
   
  def get_user_ip
    request.location
  end
  
  def get_city(input_string)
    input_string.split(',')[0].strip.titleize
  end  

  def get_state(input_string)
    split_result = input_string.split(',')
    split_result.length > 1 ? split_result[1].strip.upcase : nil
  end
  
end

app/helpers/rides_helper.rb
module RidesHelper

  def compass_points(bearing)
    return "North" if 0 <= bearing && bearing <= 22.5 || 337.5 < bearing && bearing <= 360
    return "Northeast" if 22.5 < bearing && bearing <= 67.5
    return "East" if 67.5 < bearing && bearing <= 112.5
    return "Southeast" if 112.5 < bearing && bearing <= 157.5
    return "South" if 157.5 < bearing && bearing <= 202.5
    return "Southwest" if 202.5 < bearing && bearing <= 247.5
    return "West" if 247.5 < bearing && bearing <= 292.5
    return "Northwest" if 292.5 < bearing && bearing <= 337.5
  end

  def ridetime(ride)
    day = ride.go_time.strftime("%a")
    date = ride.go_time.strftime("%b %d")
    if ride.go_time.hour < 12
      hour = ride.go_time.strftime("%l") + "am"
    else
      hour = ride.go_time.strftime("%l") + "pm"
    end
    [day, date, hour]
  end
  
  def ride_showtime(ride)
    t = @ride.go_time.strftime("%A, %B %d at %l:%M")
    return t + " am" if @ride.go_time.hour < 12
    return t + " pm" if @ride.go_time.hour >= 12
  end
  
  def bikes_with(count, offered)
    if offered
      return "No room for bikes" if count == 0
      return "1 bike in the trunk" if count == 1
      return "1 bike on a rack" if count == 2
      return "2 bikes on a rack" if count == 3
      return "3 bikes on a rack" if count == 4
    else 
      return "No bike" if count == 0
      return "1 bikes" if count == 1
      return "2 bikes" if count == 2
      return "3 bikes" if count == 3
    end
  end
  
  def smoking_pref(smoking, offered)
    if offered
      return "No smoking" if smoking == 0
      return "No smoking in the car" if smoking == 1
      return "OK to smoke in the car" if smoking == 2
      return "I smoke in the car" if smoking == 3
    else 
      return "Non-smoker" if smoking == 0
      return "Occasional smoker" if smoking == 1
      return "Smoker" if smoking == 2
      return "Heavy smoker" if smoking == 3
    end
  end 
  
end

app/views/rides/_form.html.erb
<%= simple_form_for @ride, :class=> "form-inline ride center" do |f| %>

    <h2 class="happy_monkey center">
	ride:
	<%= f.select :offered, [['offered', true], ['wanted', false]] %>
	</h2><br>

	<span class="city_label happy_monkey">from: </span>
	<%= f.text_field :start_city, :placeholder => "(city)" %>
    <%= state_select(f, :start_state) %></span><br>
    <span class="city_label">to: </span>
    <%= f.text_field :end_city, :placeholder => "(city)" %>
	<%= state_select(f, :end_state) %>

    <br style="clear:both;"><br>

	<span class="city_label">on: </span>
	<%= f.date_select :go_time, {:order => [:month, :day], :style => "width:60px", :default => Date.today } %> 
	<br>
    <span class="city_label"> at: </span>
    <%= go_time_select(f, :go_time_hour, @ride.go_time.hour) %>
    <%= go_time_min_select(f, :go_time_min, @ride.go_time.min) %>
    <br style="clear:both;">  <br>  
    <div class="center"><%= f.submit "continue", :class => "btn btn-warning" %></div>

<% end %>

app/views/rides/_index.html.erb
<% provide :title, "rides" %>
  <div class="hero-unit">

    <h1 style="font-size: 3em;">
	rides
	<p id="rides_subtitle">
	<% unless params[:action] == "user_rides" %>
	   <%= params[:action] %>
	<% else %>
	  posted by <%= @user.username %>
	<% end %>
	</p>
    </h1>
	<div class="woohoo round">
	showing
	<span class="ride_count"><%= pluralize(@rides.count, "ride") %></span>
	</div>
  </div>

  <div class="shade round ride_container">
	<div id="ride_search"><%= render 'shared/ride_search' %></div>

  <div id="rides_table">	
    <%= render 'rides_table' %>
  </div>

</div>

app/views/rides/_ride.html.erb
<tr>
  
  <td class="avatar">
	<%= gravatar_for ride.user, :thumb, :size => 30 %>
  </td>
  <td class="user">

    <%= link_to ride.user.username, ride.user %> 
  </td>
  <td class="">
    <%= link_to "#{ridetime(ride)[0]} #{ridetime(ride)[1]} #{ridetime(ride)[2]}", ride %>
  </td>
  <td class="cities">
    <strong>
    <%= "#{ride.start_city}, #{ride.start_state}" %>
    </strong> 
  </td>
  <td class="">
    to 
  </td>
  <td>
    <strong>
     <%= "#{ride.end_city}, #{ride.end_state}" %>
    </strong> 
  </td>
  <td class="alt ride_hide_small">
    <%= time_ago_in_words(ride.created_at) %> 
    ago.
  </td>
</tr>

app/views/rides/_rides_table.html.erb
<table class="table table-condensed rides round_bottom shadow">
<% unless @rides.blank? %>
  <%= render @rides %>
<% else %>
  <tr><td colspan="7"><h3 align="center">no rides matched your search</h3></tr>	
<% end %>
	
<tr><td id="pagination" colspan=7>
<%= will_paginate @rides, :class => "apple_pagination" unless controller_name == "pages" %>
</tr>

</table>

app/views/rides/edit.html.erb
<div class="hero-unit"><h1>edit ride</h1></div>

<%= form_for @ride do |f| %>
  <%= render 'form', :f => f %>
<% end %>

app/views/rides/home_search.js.erb
if ($("select option:selected").text() == "rider") {
  $("#home_page_search").html("<%= escape_javascript(render("pages/home_search_wanted")) %>");
}
else {
  $("#home_page_search").html("<%= escape_javascript(render("pages/home_search_offered")) %>");
}

app/views/rides/index.html.erb
<%= render 'index' %>

app/views/rides/index.js.erb
if ($("#rides_table").length) {
  $("#rides_table").html('<%= j render('rides_table') %>');
  $(".woohoo").html("showing <%= pluralize(@rides.count, "ride") %>");
  $("#rides_subtitle").text
	('<%= j %w[offered wanted].include?(params[:action]) ? 
		params[:action] : 
		"posted by " + current_user.username %>');
  $("#ride_search").html('<%= j render('shared/ride_search') %>');
}
else {
  $("#body").html("<%= escape_javascript(render("rides/index")) %>");
}

app/views/rides/index_wanted.html.erb
<!-- <% provide :title, "rides" %>

  <div class="hero-unit">
    <h1>rides</h1><p>wanted</p>
  </div>

  <div class="shade round ride_container">
	<%= render 'shared/ride_search' %>

  <div id="rides_table">

    <%= render 'rides_table' %>
  </div>
</div> -->

app/views/rides/index_wanted.js.erb
$("#rides_table").html("<%= escape_javascript(render("rides_table")) %>");

app/views/rides/new.html.erb
<% provide(:title, "post ride") %>
<div class="hero-unit">
  <div style="float: right;"><%= gravatar_for(current_user, :small, :size => 100) %></div>
  <h1>whithr.to
	  <p>from where to where and when?
  </h1>
</div>
<div class="small-container">
  <div class="small-container">
    <div class="">
      <%= form_for @ride do |f| %>
        <%= render 'form', :f => f %>
      <% end %>
    </div>
  </div>
</div>

app/views/rides/show.html.erb
<div class="hero-unit" style="padding-left:5%;">
  <div class="row">
    <div class="span2">
      <%= link_to  (gravatar_for @ride.user, :small, :size => 100), @ride.user %>
      <h2><%= link_to @ride.user.username, @ride.user %></h2>
    </div>
    <div class="well span6" style="padding-top: 0px;">
      <div class="content round center" style="font-weight: bold; margin-bottom: 10px; background-color: #fff;">
        <% if @ride.user == current_user %>   
        <%= best_in_place @ride, :offered, :type => :select, :collection => [[true, "ride offered"], [false, "ride wanted"]] %>
		<% else %>
		<%= @ride.offered? ? "ride offered" : "ride wanted" %>
        <% end %>
	  </div>
	  <%= best_in_place_if @ride.user == current_user, @ride, :start_city %>, 
	  <% best_in_place_if @ride.user == current_user, @ride,:start_state, :type => :select, :collection => best_state_list %>
	  <%= @ride.start_state %> to 
	  <%= best_in_place_if @ride.user == current_user, @ride, :end_city %>, 
	  <% best_in_place_if @ride.user == current_user, @ride, :end_state, :type => :select, :collection => best_state_list %>
	  <%= @ride.end_state %>
	  <div class="content pos round" style="float:right; padding: 10px;">
	    <% @ride.detail.cost ||= 0 %>
	  	<h2 class="cost">
	  	  $ <%= best_in_place_if @ride.user == current_user, @ride.detail, :cost %>
	  	</h2>
      </div>
	  <h4 style="clear:left;"><%= ride_showtime(@ride)%></h4>
	  <div><br><a href="https://twitter.com/share" class="twitter-share-button" data-via="hithrto">Tweet</a>
	  	
	  	
	  	<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>	
	  	
	  	
	  </div>
	  <div>
	  	    <a name="fb_share" type="button"></a> 
	  		<script src="http://static.ak.fbcdn.net/connect.php/js/FB.Share" 
	  		        type="text/javascript">
	  		</script>
	  </div>
    </div>
    <div class="span2">
	<p>
	      <% if @ride.user == current_user %>
	        <div>
	        <%= link_to "edit", edit_ride_path(@ride), :class => "btn btn-warning" %><br/>
		    <%= link_to "delete", @ride, :confirm => "Are you sure?", :method => :delete, :class => "btn btn-danger" %>
		    </div>
		  <% else %>
		    <div>
		    <%= form_tag new_user_message_path(@ride.user), :method => :get do %>
		      <%= hidden_field_tag(:subject, "#{@ride.start_city} to #{@ride.end_city}") %>
		      <%= submit_tag "send a message", :class => "btn btn-primary" %>
		    <% end %>
		    </div>
	      <% end %>
	</p>
	</div>
  </div><div class="center"><i><%= "click the underlined fields to edit" if @ride.user == current_user %></i></div>
</div>
<!-- ride detail -->
<div class="row">
<div class="span8" style="">
	<div class="well shadow round">

  <div class="content round" style="padding: 20px; font-size:110%;">
	<p>	
	<% line_breaks(@ride.detail.message).each do |msg| %>
	  <%= msg %><br>
	<% end %>
	</p>
  <% if @ride.user == current_user %>
      <div class="center">
	  <a class="accordion-toggle" style="font-size:90%;" data-toggle="collapse" href="#edit-msg">
	  	<%= "edit" if @ride.detail.message.present? %>
		<%= "add a message" if !@ride.detail.message.present? %>
	  </a>
	  </div>
	  <div id="edit-msg" class="accordion-body collapse" style="clear:both;">
	  <div class="center"><br>
	  <%= simple_form_for @ride.detail do |f| %>
	    <%= f.input :message, :label => "info: ", :placeholder => "...what, where, how? etc" %>
	    <%= f.submit "update", :class => "center btn" %>
	  <% end %>
	  </div>
	  </div>
  <% end %>
  </div>
  <div class="round-top ride-detail">
  <% @ride.offered ? seats = 'available' : seats = 'wanted' %><b>seats <%= seats %>: </b></div>
  <div style="float:left; padding: 10px 5px 0 5px;">
    <%= best_in_place_if @ride.user == current_user, @ride.detail, :seats_available, 
 		:type => :select, :collection => 
		[[1, "1"], [2, "2"], [3, "3"], [4, "4"], 
		[5, "5"], [6, "6"], [7, "7"], [8, "8"]] %>
  </div><br>

  <div class="ride-detail"><b>radio: </b></div>
  <div style="float:left; padding: 10px 5px 0 5px;">
    <%= best_in_place_if @ride.user == current_user, @ride.detail, :radio,
 		:type => :select, collection: 
		[["Flexible", "Flexible"], ["Music", "Music"], 
		["NPR", "NPR"], ["Talk radio", "Talk radio"], ["Nothing", "Nothing"]] %>
  </div><br><br>


  <div class="ride-detail"><b>bikes: </b></div> 
  <div style="float:left; padding: 10px 5px 0 5px;">
  <% if @ride.user == current_user %>
    <% if @ride.offered == true %>
    <%= best_in_place @ride.detail, :bikes, 
 		:type => :select, :collection => 
		[[0, "No bikes"], [1, "1 bike in the trunk"], 
		[2, "1 bike on a rack"], [3, "2 bikes on a rack"], [4, "3 bikes on a rack"]] %>
	<% else %>
	<%= best_in_place @ride.detail, :bikes, 
 		:type => :select, :collection => 
		[[0, "No bike"], [1, "1 bike"], 
		[2, "2 bikes"], [3, "3 bikes"]] %>
	<% end %>
  <% else %>
    <%= bikes_with(@ride.detail.bikes, @ride.offered) %>
  <% end %>
  </div><br><br>

  <div class="round-bottom ride-detail"><b>smoking: </b></div> 
  <div style="float:left; padding: 10px 5px;">
  <% if @ride.user == current_user %>
    <% if @ride.offered %>
      <%= best_in_place @ride.detail, :smoking, 
		:type => :select, :collection => 
		[[0, "No smoking"], [1, "No smoking in the car"], 
		[2, "OK to smoke in the car"], [3, "I smoke in the car"]] %>  
	<% else %>
	  <%= best_in_place @ride.detail, :smoking, 
		:type => :select, :collection => 
		[[0, "Non-smoker"], [1, "Occasional smoker"], 
		[2, "Smoker"], [3, "Heavy smoker"]] %>
	<% end %>
  <% else %>
    <%= smoking_pref(@ride.detail.smoking, @ride.offered) %>
  <% end%>
</div><br><br><br><br><br><br>

<% if @ride.user == current_user %><br>
<div class="center"><%= link_to "Create Return Trip", return_trip_path(@ride), :class => "btn btn-primary" %><br><br></div>
<% end %>
</div>
</div>



<div class="span4" style="margin-left:0px; margin-right:0px;">
	<div class="well round shadow">
   <p class="heading">Heading ~<%= @ride.trip_distance.round %> miles 
      <%= compass_points(@ride.bearing) %>
   </p>
    from:<br/>
<%= image_tag "http://maps.google.com/maps/api/staticmap?size=225x150&sensor=false&zoom=7&markers=#{@ride.latitude}%2C#{@ride.longitude}" %>
    <br><br>to: <br/>
    <%= image_tag "http://maps.google.com/maps/api/staticmap?size=225x150&sensor=false&zoom=7&markers=#{@ride.end_lat}%2C#{@ride.end_long}" %>
<br><br>
  <% map_link = 'http://maps.google.com/maps?saddr=' + @ride.start_city + ',+' + @ride.start_state + '&daddr=' + @ride.end_city + ',+' + @ride.end_state %>
  <p class="heading"><%= link_to "See route on Google Maps", map_link %></p>
  </tr>
</table>
</div>
</div>

app/views/rides/user_rides.html.erb
<!-- <% provide :title, "rides" %>

  <div class="hero-unit">
    <h1>my rides</h1><br>
  </div>
<div class="small-container">
  <%= render 'shared/ride_search' %>
  <div id="rides_table">
    <%= render 'rides_table' %>
  </div>
</div> -->

app/views/rides/user_rides.js.erb
$("#rides_table").html("<%= escape_javascript(render("rides_table")) %>");